// This file is generated. Do not edit this file.
// Original file: /pipeline/pipeline.go

package middleware

import (
	"github.com/lanvard/support/caller"
	"lanvard/foundation"
	"lanvard/http"
)

type Passable = http.Request
type Result = http.Response

type Destination func(data Passable) Result
type PipeInterface interface {
	Handle(data Passable, next Destination) Result
}

// noinspection GoNameStartsWithPackageName
type Pipeline struct {
	App foundation.Application

	// The object being passed through the contract.
	Passable Passable

	// the array of pipes.
	Pipes []PipeInterface
}

func NewPipeline(app foundation.Application) Pipeline {
	return Pipeline{App: app}
}

func (p Pipeline) Path() string {
	return caller.Path()
}

// Set the object being sent through the contract.
func (p Pipeline) Send(passable Passable) Pipeline {
	p.Passable = passable

	return p
}

// Set the array of pipes.
func (p Pipeline) Through(pipes []PipeInterface) Pipeline {
	p.Pipes = pipes

	return p
}

// Run the contract with a final destination callback.
func (p Pipeline) Then(destination Destination) Result {

	var callbacks []func(data Passable) Result
	var nextCallback = 0

	pipes := reverse(p.Pipes)

	for i, pipe := range pipes {
		pipe := pipe
		if i == 0 {
			// Give the last callback a destination callback
			callback := func(data Passable) Result {
				return pipe.Handle(data, destination)
			}
			callbacks = append(callbacks, callback)
		} else {
			// Give other callback the next callback
			callback := func(data Passable) Result {
				nextCallback--
				return pipe.Handle(data, callbacks[nextCallback])
			}
			callbacks = append(callbacks, callback)
		}
	}

	nextCallback = len(callbacks) - 1

	return callbacks[nextCallback](p.Passable)
}

func reverse(pipes []PipeInterface) []PipeInterface {
	for left, right := 0, len(pipes)-1; left < right; left, right = left+1, right-1 {
		pipes[left], pipes[right] = pipes[right], pipes[left]
	}

	return pipes
}
